name: Update Profile Cards

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate Profile Stats Card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          path: profile/cards/stats.svg
          token: ${{ secrets.PAT }}
          options: username=${{ github.repository_owner }}&theme=github_dark&show_icons=true&hide=commits&hide_title=true&hide_rank=true

      - name: Generate Profile Top Languages Card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          path: profile/cards/top-langs.svg
          token: ${{ secrets.PAT }}
          options: username=${{ github.repository_owner }}&theme=github_dark&hide_title=true&layout=compact

      - name: Commit Profile Cards
        run: |
          git config user.name "omardiaadev"
          git config user.email "contact@omardiaa.dev"
          git add profile/cards/*.svg
          git commit -m "Update Profile Cards" || exit 0
          git push
